alphagov/paas-aiven-broker

ci/integration/integration_test.go
provider/provider.go
provider/provider_internals_test.go
provider/provider_test.go

The instance name was previously limited to 16 characters, so we had to
hash the instanceID (a GUID) using crc32 to get something that would
fit.
Since then Aiven have relaxed this limit and it's now possible to
use instance names up to 64 characters. This therefore removes the crc32
hashing, and merely appends the instanceID to the prefix.
I've taken this opportunity to refactor some of the internal functions in the provider
package so that they're no longer exported. See commits for details.
Code review.  Verify all the tests still pass.
Not me.

[#158688475] No longer hash GUID in instance name.

---

Makefile
provider/aiven/client.go
provider/aiven/client_test.go
provider/provider.go
provider/provider_test.go

To provide additional security to the elasticsearch endpoints the PaaS
egress IPs will be specified as a whitelist on the brokered instances,
preventing connections from other sources.
1. Run unit tests (`make unit`)
1. From `paas-cf`: `SELF_UPDATE_PIPELINE=false BRANCH=elasticsearch_ip_whitelist make dev pipelines`
1. Create an `elasticsearch` service instance, bind it to an app and then test connectivity (I used `cf ssh` and `curl` from a staticfile app in my testing)
1. Verify that you cannot connect from elsewhere (I used my laptop at home on and off the VPN).
Anyone but me.

[#159492539] Add IP whitelisting.

---

Makefile
ci/integration/integration_test.go

This PR adds a negative integration test to the Aiven Elasticsearch broker, and modifies an existing integration test. Taken together, these assert that Aiven's IP whitelist works as advertised.
This is being added as part of the review of the previously (prematurely-merged) PR on the same story.
@blairboy362 and myself are doing&reviewing.

[#159492539] Add IP whitelisting integration testing

---

manifest.yml

1.10.2 is not available in the new go buildpack. This commit updates go
to a version that is available throughout the update process.
Code review and automated tests
Not @LeePorte

Update go version for buildpack upgrades

---

ci/integration/integration_test.go
provider/aiven/client.go
provider/aiven/client_test.go
provider/provider.go
provider/provider_test.go

We want to support plan changes of the service instances provided by this broker. Some plan changes are not supported by aiven itself. If the user tries to do an invalid operation the broker should reply with the right error.
The update service logic was already implemented. But for performing the instance update we must also include
the user_config struct with specifies the elasticsearch
version and IP filter.
Including the ES version would allow do version upgrades, and
the IP filter is needed to avoid potentially wiping the
existing values.
Additionally, Aiven would return an error if the udate is not
possible: major version downgrade, clustered to unclustered changes,
etc. This error is returned as 400 status and a json with the
human readable error.
We capture this error and return …

[#159845792] Service update include user config and errors

---

manifest.yml

By specifying this as 1.10 instead of 1.10.3 we'll get the latest patch
version of 1.10 that's available in the buildpack. At present we're
getting the following warning when deploying:
```
**WARNING** A newer version of go is available in this buildpack. Please adjust
your app to use version 1.10.4 instead of version 1.10.3 as soon as possible. Old
versions of go are only provided to assist in migrating to newer versions.
```
From the buildpack docs[1]:
> When specifying versions, specify only major/minor versions, such as
> Go 1.6, rather than Go 1.6.0. This ensures you receive the most recent
> patches.
I've confirmed that when pushing this app with 1.10 specified it
currently picks up 1.10.4
[1]https://docs.cloudfoundry.org/buildpacks/go/index.html#pushing_apps
Describe what you have …

Relax Go version in the CF manifest.

---

provider/aiven/client.go
provider/aiven/client_test.go

Aiven released the stable v1 API on 31 Dec[1]. This is identical to the
v1beta API that we've been using up until now, it just has a different
prefix.
[1]https://aiven.io/changelog#2018-12-31
Code review. Verify all the tests pass.
Not me.

Use stable v1 Aiven API

---

ci/integration/integration_test.go
client/elastic/client.go
client/elastic/client_test.go
provider/provider.go
provider/provider_test.go

We've seen issues where the credentials returned by the Aiven API don't
work for a short period after creation - the ES endpoint returns 401
errors. This has caused things like our acceptance tests to fail.
This adds a polling loop to the bind call to wait until the credentials
successfully connect. Becuase this is only a best-effort workaround, if
the polling times out, it returns anyway.
With this in place, there's no longer a need to have the polling in the
integration tests, so this is also removed.
* Code review
* Verify all tests pass.
Not me.

[#164045929] Fix user creation delay

---

ci/integration/integration_test.go

Elasticsearch 5.x is at its end of life and no longer being provided by the broker. This commit removes the integration tests for it.
Code review and check the integration tests passed.
Not @tnwhitwell or @AP-Hunt

Remove Elastisearch 5.x integration tests

---

provider/aiven/client.go
provider/aiven/client_test.go

In a recent support ticket, a tenant reported that unbinding their app from an Elasticsearch was failing:
> Service broker error: Error deleting service user: 403 status code returned from Aiven: `'{"errors":[{"message":"Service user 'GUIDGUID-GUID-GUID-GUID-GUIDGUIDGUID' does not exist`
(Where GUID is a placeholder for the real GUID involved.)
I investigated and found that on the first attempt to unbind, Aiven returned a `502 Bad Gateway` error when the broker attempted to delete the binding's Elasticsearch user. It seems that Aiven did delete the user despite that error response.
This commit has the broker detect when a user does not exist, such as when it has already been deleted. This should prevent this problem from recurring and help maintain our tenants' confidence in us.
* See if …

Improve resiliency of Unbind to errors from Aiven

---

manifest.yml

The Go buildpack deployed to the PaaS has dropped support for Go 1.10 as of [1.8.41](https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.8.41).
1. Code review
1. Check the integration tests
Anyone

[#167506774] Bump version of Golang used to 1.12

---

ci/integration.yml

Gets the `AIVEN_API_TOKEN` and `AIVEN_PROJECT` secrets from Credhub, instead of the S3 secrets files.
1. See [the matching change in `paas-release-ci`](https://github.com/alphagov/paas-release-ci/pull/136)
Anyone

[#170180331] Use Credhub for secrets in integration test pipeline

---

provider/credentials.go
provider/credentials_test.go

When generating prometheus remote read configuration we should set read_recent to be true, so that prometheus goes to influx to get metrics
Otherwise prometheus may not read the metrics from the remote, depending on how recently prometheus has been started
CI
To demonstrate this for a paas prometheus instance:
- `cf restart prometheus-service`
- Browse the graph page with `up` and verify that only recent results are displayed
- `cf ssh` onto the instance and add `"read_recent": true` to the `remote_read` section
- (SIGHUP) `kill -1 $prometheus pid`
- Browse the graph page with `up` and verify that all results are displayed
@paroxp

Force prometheus to read recent from remote

---

ci/integration/integration_test.go
provider/credentials.go
provider/credentials_test.go

includes the name of the provided database in the binding credentials 
so that we have all the information required in VCAP_SERVICES to start reading/writing to the database.
the influxdb username/password/host/port provided in the credentials are not enough to connect and start using the database ... you also need to either create a database or use an existing one.
the provided credentials do not have permission to create databases, so we need to know the name of the database that is provided for us.
the database name "defaultdb" appears currently hardcoded in the prometheus-specific configuration credentials, but it isn't fun to parse it from there or to hardcoded it anywhere incase it changes.

include influxdb database name in binding credentials

---

ci/integration/integration_test.go

ES 6.x is no longer offered by Aiven as it's EOL so we can't use it to test any
longer. THis commit updates the tests to use ES 7.x.
Code review
Check the tests pass
Anyone

Update ES integration tests to use 7.x

---

README.md

The pipelines are currently broken after removing TLWR from the
"trusted" people. This is unfortunate, when it comes to repos that
require signed commits, but also aren't maintained very often.
Concourse is likely to ignore an empty signed commit. Meaning there
needs to be a codebase change for the pipelines to kick through.
Adding the timestamp to the readmem which is essentially a HTML comment,
will satisfy that problem, and allow us to bump the codebase without
finding perhaps unknown bugs.
- Sanity check

Add timestamp change

---

go.mod
manifest.yml

Bump the required version of golang in the module and cf manifest to 1.16, because we're about to roll out a buildpack which removes 1.15.
Set a dev pipeline's `paas-aiven-broker` resource's `branch` to this one?
Human engineers.
---
🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

[#179252161] bump golang to 1.16

---

.github/dependabot.yml
.github/workflows/pr.yml

- Pin GitHub actions to hashes
- Turn on dependabot to open PRs for GitHub actions
🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

BAU - Add dependabot for GitHub actions

---

.github/workflows/pr.yml
go.mod
go.sum
manifest.yml

Use go v1.21
A recent go buildpack update is dropping support for go 1.20, so updating to 1.21 will let us update this buildpack
Ensure that the aiven broker deploys okay to a dev environment and passes tests
Current PaaS team members
---
🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

Update to go 1.21

---

.github/workflows/pr.yml
go.mod
manifest.yml

Use go v1.22
> Initially intended to upgrade go to 1.23, but reverted to 1.22 due to current buildpack compatibility. Buildpack doesn't yet support 1.23.
To be up to date with the go buildpacks
Ensure that the aiven broker deploys okay to a dev environment and passes tests
Current PaaS team members
---
🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

Upgrade go to 1.22
